openapi: "3.0.1"
info:
  version: "1.0.0-alpha1"
  title: "pg-ledger API"
  description: "API to access the pg-ledger database."
  license:
    name: "GNU Affero General Public License version 3"
    url: "https://www.gnu.org/licenses/agpl.txt"
paths:
  /accounts:
    get:
      description: "Gets all accounts."
      parameters:
      - name: "skip"
        in: "query"
        required: false
        description: "Skip this many accounts. If not specified, this should default to 0."
        schema:
          type: "number"
      - name: "take"
        in: "query"
        required: false
        description: "Take this many accounts. If not specified, this should default to 100."
        schema:
          type: "number"
      responses:
        '200':
          description: "A list of accounts, ordered by full name."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  totalCount:
                    type: "number"
                  accounts:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        accountFullName:
                          type: "string"
      tags:
      - "Accounts"
    post:
      description: "Adds a new account with the specified full name."
      requestBody:
        description: "The account to add."
        content:
          application/json:
            schema:
              type: "object"
              properties:
                accountFullName:
                  type: "string"
        required: true
      responses:
        '201':
          description: "The account was successfully added."
        '409':
          description: "The account with the specified name already exists."
      tags:
      - "Accounts"
  /accounts/balances:
    get:
      description: "Gets the balances of all accounts."
      responses:
        '200':
          description: "A list of accounts with balances."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    accountFullName:
                      type: "string"
                    balance:
                      type: "array"
                      items:
                        type: "object"
                        properties:
                          commoditySymbol:
                            type: "string"
                          balance:
                            type: "number"
      tags:
      - "Accounts"
  /accounts/{accountFullName}:
    parameters:
    - name: "accountFullName"
      in: "path"
      required: true
      description: "The full name of the account"
      schema:
        type: "string"
    get:
      description: "Gets the account with the specified name."
      responses:
        '200':
          description: "The account exists, and is returned."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  accountFullName:
                    type: "string"
        '404':
          description: "The account does not exist."
      tags:
      - "Accounts"
    delete:
      description: "Deletes the account with the specified name."
      responses:
        '204':
          description: "The account was successfully deleted."
        '400':
          description: "The account could not be deleted."
        '404':
          description: "The account does not exist."
      tags:
      - "Accounts"
  /accounts/{accountFullName}/balance:
    parameters:
    - name: "accountFullName"
      in: "path"
      required: true
      description: "The full name of the account"
      schema:
        type: "string"
    get:
      description: "Gets the balance of the account with the specified name."
      responses:
        '200':
          description: "The account exists, and its balances are returned."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    commoditySymbol:
                      type: "string"
                    balance:
                      type: "number"
      tags:
      - "Accounts"
  /commodities:
    get:
      description: "Gets all commodities."
      parameters:
      - name: "skip"
        in: "query"
        required: false
        description: "Skip this many commodities. If not specified, this should default to 0."
        schema:
          type: "number"
      - name: "take"
        in: "query"
        required: false
        description: "Take this many commodities. If not specified, this should default to 100."
        schema:
          type: "number"
      responses:
        '200':
          description: "A list of commodities, ordered alphanumerically by symbol."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  totalCount:
                    type: "number"
                  commodities:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        symbol:
                          type: "string"
                        isPrefix:
                          type: "boolean"
                        hasSpace:
                          type: "boolean"
      tags:
      - "Commodities"
    post:
      description: "Adds a new commodity with the specified properties."
      requestBody:
        description: "The commodity to add."
        content:
          application/json:
            schema:
              type: "object"
              properties:
                symbol:
                  type: "string"
                isPrefix:
                  type: "boolean"
                hasSpace:
                  type: "boolean"
        required: true
      responses:
        '201':
          description: "The commodity was successfully added."
        '409':
          description: "The commodity with the specified symbol already exists."
      tags:
      - "Commodities"
  /commodities/{symbol}:
    parameters:
    - name: "symbol"
      in: "path"
      required: true
      description: "The commodity's symbol"
      schema:
        type: "string"
    get:
      description: "Gets the commodity with the specified symbol."
      responses:
        '200':
          description: "The commodity exists, and is returned."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  symbol:
                    type: "string"
                  isPrefix:
                    type: "boolean"
                  hasSpace:
                    type: "boolean"
        '404':
          description: "The commodity does not exist."
      tags:
      - "Commodities"
    put:
      description: "Updates the commodity with the specified symbol."
      requestBody:
        description: "The new values of the commodity's properties."
        content:
          application/json:
            schema:
              type: "object"
              properties:
                isPrefix:
                  type: "boolean"
                hasSpace:
                  type: "boolean"
      responses:
        '204':
          description: "The commodity was successfully updated."
        '404':
          description: "The commodity does not exist."
      tags:
      - "Commodities"
    delete:
      description: "Deletes the commodity with the specified symbol."
      responses:
        '204':
          description: "The commodity was successfully deleted."
        '400':
          description: "The commodity could not be deleted."
        '404':
          description: "The commodity does not exist."
      tags:
      - "Commodities"
  /transactions:
    get:
      description: "Gets all transactions."
      parameters:
      - name: "skip"
        in: "query"
        required: false
        description: "Skip this many transactions. If not specified, this should default to 0."
        schema:
          type: "number"
      - name: "take"
        in: "query"
        required: false
        description: "Take this many transactions. If not specified, this should default to 100."
        schema:
          type: "number"
      responses:
        '200':
          description: "A list of transactions, ordered by latest first followed by descending insertion order."
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  totalCount:
                    type: "number"
                  transactions:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        id:
                          type: "string"
                          format: "uuid"
                        date:
                          type: "string"
                          format: "date"
                        text:
                          type: "string"
                        insertionOrder:
                          type: "number"
                        rows:
                          type: "array"
                          items:
                            type: "object"
                            properties:
                              id:
                                type: "string"
                                format: "uuid"
                              accountFullName:
                                type: "string"
                              commoditySymbol:
                                type: "string"
                              amount:
                                type: "number"
      tags:
      - "Transactions"
tags:
- name: "Accounts"
  description: "Operations that can be performed on accounts."
- name: "Commodities"
  description: "Operations that can be performed on commodities."
- name: "Transactions"
  description: "Operations that can be performed on transactions."
- name: "Formulas"
  description: "Operations that can be performed on formulas."
