openapi: "3.0.1"
info:
  version: "1.0.0-alpha1"
  title: "pg-ledger API"
  description: "API to access the pg-ledger database."
  license:
    name: "GNU Affero General Public License version 3"
    url: "https://www.gnu.org/licenses/agpl.txt"
paths:
  /accounts:
    get:
      description: "Gets all accounts."
      responses:
        '200':
          description: "A list of accounts."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    account_full_name:
                      type: "string"
    post:
      description: "Adds a new account with the specified full name."
      requestBody:
        description: "The account to add."
        content:
          application/json:
            schema:
              type: "object"
              properties:
                account_full_name:
                  type: "string"
        required: true
      responses:
        '201':
          description: "The account was successfully added."
        '409':
          description: "The account with the specified name already exists."
  /accounts/balances:
    get:
      description: "Gets the balances of all accounts."
      responses:
        '200':
          description: "A list of accounts with balances."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    account_full_name:
                      type: "string"
                    balance:
                      type: "array"
                      items:
                        type: "object"
                        properties:
                          commoditySymbol:
                            type: "string"
                          balance:
                            type: "number"
